"""Validate that all file paths referenced in a project exist on disk."""

from __future__ import annotations

import sys
from pathlib import Path

HERE = Path(__file__).parent


def _is_file_source(source: str) -> bool:
    """True if source is a local path that should already exist (not a URI,
    memory layer, or derived output that make prepare would generate)."""
    if ":" in source.split("/")[0]:  # http-header:, wms:, etc.
        return False
    if source.startswith("memory?"):
        return False
    if source.startswith("./output/"):  # generated by make prepare, not yet present
        return False
    return True


def validate(project_dir: Path) -> bool:
    if str(HERE) not in sys.path:
        sys.path.insert(0, str(HERE))

    from render import _abs_source, _load_spec

    spec = _load_spec(project_dir)
    errors: list[str] = []

    for layer in spec.layers:
        if layer.style_xml is not None:
            xml_path = project_dir / layer.style_xml
            if not xml_path.exists():
                errors.append(f"  [{layer.id}] style_xml not found: {xml_path}")

        if _is_file_source(layer.source):
            abs_path = Path(_abs_source(layer.source, project_dir).split("|")[0])
            if not abs_path.exists():
                errors.append(f"  [{layer.id}] source not found: {abs_path}")

    if errors:
        print(f"validation failed ({project_dir.name}):")
        for e in errors:
            print(e)
        return False

    print(f"ok ({project_dir.name}, {len(spec.layers)} layers)")
    return True


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python validate.py <project_dir>")
        sys.exit(1)
    ok = validate((HERE / sys.argv[1]).resolve())
    sys.exit(0 if ok else 1)
